### ISSUE TITLE
Add magic field name to represent the original JSON row.

### ISSUE THREAD

**Issue by halfak** [tapilab/json2tsv#4]
Sometimes you want to output the entire JSON blob as a column in the TSV.  

I propose we use the "-" special character since it is already used by many coreutils to mean: _output what was passed through stdin_.  E.g. with cat:

```
$ echo "foo" > foo.txt
(2.7)[halfak@graphite: ~/projects/json2tsv]
$ echo "bar" | cat foo.txt - 
foo
bar
```

Outputting the entire JSON object is useful when interfacing with coreutils sort. E.g. 

```
$ cat unsorted.json | json2tsv id - | sort -k1,1 | cut -f2 > sorted.json
```

**Comment by aronwc** [comment]
Sounds good. 

Thanks for improving this library. I've added you as a collaborator -- feel free to push to master directly.

**Comment by halfak** [comment]
\o/  Thanks.  Happy to be contributing here :)

**Comment by halfak** [comment]
It looks like I don't yet have rights to push to this repo.

**Comment by aronwc** [comment]
@halfak : sorry, invite sent
